# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'APN-Subscription'
    azureContainerRegistry: '{"loginServer":"puffersofttest.azurecr.io", "id" : "/subscriptions/eeb9dfdd-9c17-44c3-a4a0-7529399ce200/resourceGroups/AzureDevOps-demo-rg/providers/Microsoft.ContainerRegistry/registries/puffersofttest"}'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: |
      ## do not put this file under version control!
      SECRET_KEY='c_r-e8v1divj8y+hu@-w=n#$xj#ciuejybd3_(k2h789(mcv8$'
      DEBUG=False
      
      ## Super-User Credentials
      SUPER_USER_NAME = 'root'
      SUPER_USER_PASSWORD = 'root'
      SUPER_USER_EMAIL = 'admin@email.com'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker-compose up'
    arguments: '--build'